package emailvalidator

// Initial list is based on Limits on Role-based Addresses: https://eepurl.com/dyil9Y
var blackList = map[string]bool{
	"abuse":                  true,
	"admin":                  true,
	"billing":                true,
	"compliance":             true,
	"devnull":                true,
	"dns":                    true,
	"ftp":                    true,
	"hostmaster":             true,
	"inoc":                   true,
	"ispfeedback":            true,
	"ispsupport":             true,
	"list-request":           true,
	"list":                   true,
	"maildaemon":             true,
	"noc":                    true,
	"no-reply":               true,
	"noreply":                true,
	"null":                   true,
	"phish":                  true,
	"phishing":               true,
	"postmaster":             true,
	"privacy":                true,
	"registrar":              true,
	"root":                   true,
	"security":               true,
	"spam":                   true,
	"support":                true,
	"sysadmin":               true,
	"tech":                   true,
	"undisclosed-recipients": true,
	"unsubscribe":            true,
	"usenet":                 true,
	"uucp":                   true,
	"webmaster":              true,
	"www":                    true,
}
